name: news_reader_app
description: A feature-rich news reader app in Flutter.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  fluttertoast: ^8.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/mock_news_data.json
